### ISSUE TITLE
similar to config.action_view.raise_on_missing_translations behavior?

### ISSUE THREAD

**Issue by Fedcomp** [collectiveidea/interactor-rails#15]
Rails, when `config.action_view.raise_on_missing_translations` is active, will raise errors in case of missing translations.
However it's not the case for this gem:

``` ruby
interactor.errors.messages
=> {:login=>["translation missing: en.active_interaction.errors.models.confirm_phone.attributes.login.confirmation_token_expired"]}
```

Maybe gem should use `config.action_view.raise_on_missing_translations` var and use raise them too (because gem is rails only), or have own variable for the same purpose?

**Comment by laserlemon** [comment]
Interactor doesn't do any I18n translation or localization itself so I think what you're experiencing must be due to your own application code or an interaction with some other gem. Please feel free to submit an example failing case and I can take a look. In the meantime, I'll close this issue. Thank you!
